---
title: "About"
---

About this site

```{r echo = FALSE, include=FALSE}

library(data.table)
library(magrittr)
library(dplyr)
#library(leaflet)
#library(tidyverse)
#library(devtools)
library(R.utils)
#library(lubridate)
library(ggplot2)
library(knitr)
library(kableExtra)

library(dtplyr)
library(dplyr)

#library(readxl)
```

```{r echo=FALSE}

#hd <- read_excel(file.path("~", "Downloads","heart_disease_health_indicators_BRFSS2015.xlsx"))
hd <- data.table::fread(file.path("~", "Downloads","heart_disease_health_indicators_BRFSS2015.csv"))

hd$HDorAttack <- ifelse(hd$HeartDiseaseorAttack==1,"Yes","No")
hd$Gender <- ifelse(hd$Sex==1,"Male","Female")
hd$HighBloodPressure<- ifelse(hd$HighBP==1,"Yes","No")
hd$HighCholestrol<- ifelse(hd$HighChol==1,"Yes","No")
hd$HadStroke<- ifelse(hd$Stroke==1,"Yes","No")
hd$Smokes<- ifelse(hd$Smoker==1,"Yes","No")
hd$Exercise<- ifelse(hd$PhysActivity==1,"Yes","No")
hd$HeavyAlcoholuse<- ifelse(hd$HvyAlcoholConsump==1,"Yes","No")
hd$EatsVeggies<- ifelse(hd$Veggies==1,"Yes","No")
hd$EatsFruits<- ifelse(hd$Fruits==1,"Yes","No")

hd$agecat <- case_when(hd$Age == 1 ~"Age 18 to 24",
                       hd$Age == 2~"Age 25 to 29",
                       hd$Age == 3~"Age 30 to 34",
                       hd$Age == 4~"Age 35 to 39",
                       hd$Age == 5~"Age 40 to 44",
                       hd$Age == 6~"Age 45 to 49",
                       hd$Age == 7~"Age 50 to 54",
                       hd$Age == 8~"Age 55 to 59",
                       hd$Age == 9~"Age 60 to 64",
                       hd$Age == 10~"Age 65 to 69",
                       hd$Age == 11~"Age 70 to 74",
                       hd$Age == 12~"Age 75 to 79",
                       hd$Age == 13~"Age 80 or older",
                       TRUE ~ 'NA')
hd$Educ_lvl <- case_when(hd$Education == 1~"No school",
                          hd$Education == 2~"Elementary",
                          hd$Education == 3~"Some High School",
                          hd$Education == 4~"High School",
                          hd$Education == 5~"Some college",
                          hd$Education == 6~"College graduate",
                          TRUE ~ "NA")


hd$HasDiabetes <- case_when(hd$Diabetes == 0~"No Diabetes",
                             hd$Diabetes == 1~"Pre-diabetes or borderline diabetes",
                             hd$Diabetes == 2~"Diabetes",
                             TRUE~"NA"
                             )


hd$Income_cat <- case_when(hd$Income == 1~"Less than $10,000",
                            hd$Income == 2~"Less than $15,000",
                            hd$Income == 3~"Less than $20,000",
                            hd$Income == 4~"Less than $25,000",
                            hd$Income == 5~"Less than $35,000",
                            hd$Income == 6~"Less than $50,000",
                            hd$Income == 7~"Less than $75,000",
                            hd$Income == 8~"$75,000 or more",
                            TRUE~"NA"
                            )






pred<- hd[,list(HDorAttack,Gender,agecat,BMI,Educ_lvl,Income_cat,HighBloodPressure,HighCholestrol,HadStroke,HasDiabetes,Smokes,Exercise,HeavyAlcoholuse,EatsVeggies,EatsFruits)]
#pred


```

```{r echo=FALSE}
library(DT)
datatable(hd[1:100])

```

```{r echo=FALSE}
library(plotly)
p <-ggplot(pred, aes(x = HeavyAlcoholuse, colour=HDorAttack,fill = HDorAttack)) +
  geom_bar(position = "dodge",stat="count") +
  labs(x = "High Alcohol Use Status", y = "Count",title="Barplot of High Alcohol use Status by Heart Disease status") 


ggplotly(p)


proportions_alc <-  prop.table(table(pred$HDorAttack, pred$HeavyAlcoholuse), margin = 2)

rownames(proportions_alc) <- c("Heart Disease", "No Heart Disease")
colnames(proportions_alc)<- c("Alcohol Use","No Alcohol Use")
proportions_alc %>%
  knitr::kable(caption="Proportion of Heart Disease by Heavy Alocohol Use") %>%
  kableExtra::kable_styling(bootstrap_options="striped",full_width=FALSE)
```

```{r}

```
